#!/usr/bin/env python3
"""Download Playfair Display + Plus Jakarta Sans from Google Fonts and
self-host them under assets/fonts/, writing assets/css/fonts.css.

Self-hosting removes the runtime dependency on fonts.googleapis.com /
fonts.gstatic.com, which some sandboxed viewers (VS Code webviews, locked-down
intranets) block via CSP — that silently falls back to system fonts with no
visible error. Only the latin and latin-ext subsets are kept since the site
is English-only; re-run this script if new characters or font weights are
ever needed.
"""
import os
import re
import urllib.request

FAMILIES = "family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400&family=Plus+Jakarta+Sans:wght@300;400;500;600;700"
GOOGLE_CSS_URL = f"https://fonts.googleapis.com/css2?{FAMILIES}&display=swap"
KEEP_SUBSETS = {"latin", "latin-ext"}

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONTS_DIR = os.path.join(ROOT, "assets", "fonts")
CSS_OUT = os.path.join(ROOT, "assets", "css", "fonts.css")


# Google Fonts sniffs the User-Agent to decide the response: a modern desktop
# Chrome UA is required to get woff2 files split into unicode-range subsets;
# anything else (including a bare "Mozilla/5.0") falls back to a single
# unsubsetted .ttf per family with no subset comments to parse.
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req) as resp:
        return resp.read()


def local_name(family, weight, style, subset):
    fam_slug = "playfair-display" if "Playfair" in family else "plus-jakarta-sans"
    style_slug = "italic" if style == "italic" else "normal"
    return f"{fam_slug}-{weight}-{style_slug}-{subset}.woff2"


def main():
    os.makedirs(FONTS_DIR, exist_ok=True)
    css = fetch(GOOGLE_CSS_URL).decode("utf-8")

    blocks = re.findall(r"/\* (\w[\w-]*) \*/\s*(@font-face\s*\{[^}]*\})", css)
    kept = [(s, b) for s, b in blocks if s in KEEP_SUBSETS]
    if not kept:
        raise RuntimeError(
            "No subsetted @font-face blocks found in the Google Fonts response "
            "(got a non-subsetted fallback, likely a User-Agent sniffing change on "
            "Google's side) — inspect the raw response and update USER_AGENT/parsing."
        )

    url_cache = {}
    out_blocks = []
    for subset, block in kept:
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        style = re.search(r"font-style:\s*(\w+)", block).group(1)
        url = re.search(r"url\(([^)]+)\)", block).group(1)

        fname = local_name(family, weight, style, subset)
        local_path = os.path.join(FONTS_DIR, fname)
        if url not in url_cache:
            data = fetch(url)
            with open(local_path, "wb") as f:
                f.write(data)
            url_cache[url] = fname
            print(f"downloaded {fname} ({len(data)} bytes)")
        elif not os.path.exists(local_path):
            with open(os.path.join(FONTS_DIR, url_cache[url]), "rb") as src, open(local_path, "wb") as dst:
                dst.write(src.read())

        new_block = block.replace(f"url({url})", f"url('../fonts/{fname}')")
        out_blocks.append((subset, new_block))

    order = {"latin-ext": 0, "latin": 1}
    out_blocks.sort(key=lambda b: order[b[0]])

    with open(CSS_OUT, "w", encoding="utf-8") as f:
        f.write("/* Self-hosted Playfair Display + Plus Jakarta Sans (latin + latin-ext). */\n")
        f.write("/* Generated by scripts/fetch-fonts.py — do not hand-edit; re-run the script instead. */\n\n")
        for subset, block in out_blocks:
            f.write(f"/* {subset} */\n{block}\n\n")

    print(f"wrote {CSS_OUT} ({len(url_cache)} unique font files)")


if __name__ == "__main__":
    main()
